######################################################################
# Automatically generated by qmake (3.0) lun. mai 14 03:41:51 2018
######################################################################

TEMPLATE = app
TARGET = gui
INCLUDEPATH += .

# Input
HEADERS += Controls.hpp Loader.hpp MainWindow.hpp
FORMS += MainWindow.ui
SOURCES += Controls.cpp Loader.cpp main.cpp MainWindow.cpp
QT += widgets core
