######################################################################
# Automatically generated by qmake (3.0) mar. mai 29 11:34:50 2018
######################################################################

TEMPLATE = app
TARGET = gui
INCLUDEPATH += .

# Input
HEADERS += Controls.hpp Loader.hpp MainWindow.hpp SimulationScene.hpp
FORMS += MainWindow.ui
SOURCES += Controls.cpp Loader.cpp main.cpp MainWindow.cpp SimulationScene.cpp
QT += core widgets
